### ISSUE TITLE
프로젝트 주제 선정

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#1]
1. 다나와 시스템을 이용하여 사용자가 고른 제품의 가격이 설정해놓은 수치 이하로 떨어질 경우 사용자에게 알림을 주는 시스템

2. 에브리타임 어플 및 사이트 내의 장터에 올라오는 품목 중 사용자가 구매를 원하는 키워드를 설정해 놓으면 해당 품목 글이 올라올 때 알림을 주는 시스템

3. 화분의 수분상태를 모니터링하여 사용자에게 수분 필요에 대한 알림을 주도록 하는 시스템

세개 중 교수님의 의견과 회의를 통하여 주제를 정하도록 하겠습니다.
의견 남겨주세요.

**Comment by 2gunghyun** [comment]
교수님께 의견을 물어본 결과 모니터링이라는 주제와는 3번이 가장 어울리는 것으로 생각됩니다.

**Comment by wogur0915** [comment]
제 생각에도 1, 2번 주제는 모니터링이라기보단 추천시스템에 적합한 것 같아 3번 화분 수분상태 모니터링 시스템으로 주제를 결정하도록 하겠습니다.
