### ISSUE TITLE
저희 앱에 식물 관리 메뉴를 변경하고자 합니다.

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#11]
식물 관리 메뉴를 식물을 여러개 등록하는 목적에서 키우는 식물에 관한 메모나 사진과 같은 글을 저장해 놓을 수 있는 공간인 식물 일지 같은 것으로 활용 목적을 변경하려는데 의견 묻습니다.

![image](https://user-images.githubusercontent.com/34836246/197309715-b6c6cdfd-2141-4281-9ca7-1714e689b0f9.png)

첨부사진은 기존 식물 관리 탭 입니다.

**Comment by 2gunghyun** [comment]
식물을 여러개 등록하려면 장비가 그에 맞는 개수만큼 필요한데 현재 장비가 모자란만큼 차라리 식물 하나에 대한 관리쪽으로 방향을 잡으려면 이런 기능으로 바꾸는것이 좋은 것 같습니다.

**Comment by wogur0915** [comment]
> 식물을 여러개 등록하려면 장비가 그에 맞는 개수만큼 필요한데 현재 장비가 모자란만큼 차라리 식물 하나에 대한 관리쪽으로 방향을 잡으려면 이런 기능으로 바꾸는것이 좋은 것 같습니다.

알겠습니다 의견 참고하여 수정하는 방향으로 정하겠습니다.
