### ISSUE TITLE
Coding Convention 관련 논의

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#2]
앞으로 진행될 코드 작업에서 쓰일 Coding Convention에 대하여 결정하려합니다
예를 들자면 카멜체(camel case)와 스네이크체(snake case)가 있습니다.
ex) 카멜체 : appName()
      스네이크체 : app_name()

저는 평소에 카멜체를 사용하였었습니다.
기존에 사용하시던 코딩컨벤션이 있다면 코멘트 남겨주세요
하나로 통일하여 진행해야 원활할 것 같아 결정하려합니다.

**Comment by 2gunghyun** [comment]
저는 상관없으니 평소에 사용하시던 카멜체 사용하는 것이 좋을 것 같습니다.

**Comment by wogur0915** [comment]
알겠습니다. 카멜체로 통일하도록 하겠습니다.
