### ISSUE TITLE
발명설명서에 들어갈 내용을 생각해 봅시다.

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#20]
26일까지 제출해야하는 발명설명서에 들어갈 내용을 정리하는 이슈입니다.

**Comment by wogur0915** [comment]
1. 발명의 명칭
    국문 : 화분 수분 상태 모니터링 서비스 어플리케이션 (그린워터)
    영문 : Moisture of Flowerpot Monitoring Service Application (GreenWater)

**Comment by wogur0915** [comment]
2. 발명의 배경

  평소에 식물을 기르던 중 화분에 물주는 것을 종종 잊어, 이로 인해 식물이 시드는 경우를 경험함으로써 화분의 수분 부족 알람의 필요성을 느끼게 되었다. 기존의 화분 물주는 주기를 알려주는 어플리케이션들은 화분을 키우는 환경과 무관하게 단순히 정해진 주기마다 알람을 보내는 기능만 탑재하였기 때문에 정확도가 떨어지는 단점이 있어 정확한 수분 부족 알람 서비스를 제공받을 수 있도록 하고자 한다.

**Comment by wogur0915** [comment]
3. 발명의 내용

  본 고안은 토양습도센서 장치를 이용하여 사용자의 화분으로부터 토양 습도 정보를 입력받아 전용 어플리케이션에서 실시간으로 블루투스 통신을 이용하여 상태를 제공받을 수 있다. 화분의 습도 상태만 제공받을 뿐 아니라 습도 저하에 따른 알림 기능을 제공한다.

  습도에 따른 알람 제공 기능은 화분에 설치된 토양 습도 센서를 통하여 습도값을 측정하게 되고 측정된 습도값을 블루투스 BLE 통신을 이용하여 사용자의 디바이스로 제공하게 된다. 이 과정에서 측정된 습도값이 30% 이상일 경우에는 어플리케이션에서 제공하는 ‘화분 수분 상태’ 화면에 “화분이 너무 축축해요 ㅜ.ㅜ” 라는 문구를, 10%이상 30% 미만 인 경우에는 “화분의 기분이 좋아요! ^&^” 라는 문구를, 그리고 10% 미만인 경우에는 “화분이 목 말라요 ㅜ.ㅜ 물 좀 주세요!” 라는 문구를 제공한다. 또한 화분의 토양습도가 10% 미만인 건조한 경우에는 사용자에게 어플리케이션을 통한 습도 저하 알림을 제공한다.

  화분의 습도 상태 모니터링 기능 외에도 사용자가 키우는 식물에 대하여 메모를 남기거나 식물 일지를 쓸 수 있는 식물 일지 메모 기능을 제공하며, 농촌진흥청 농업기술포털인 농사로에서 ‘실내정원식물 관리법’ API를 통해 웹뷰로 식물 관리법을 제공한다.
  
  
![image](https://user-images.githubusercontent.com/34836246/202972463-70153245-9ff4-4ba9-8a5f-278494122c29.png)
  - 첨부한 시스템 블록 다이어그램은 어플리케이션을 포함한 전체적인 시스템 동작을 나타낸 것이다.

**Comment by wogur0915** [comment]
4. 발명의 효과
  
  사용자가 주기적으로 화분에 물주는 행위에 대해 주기적으로 주의를 기울이지 않아도 됨으로써 시간적 이득을 취할 수 있고, 화분에 대한 관리를 잊었을 때와 대비해 식물이 수분 부족으로 인하여 말라 죽는 경우를 방지할 수 있어 식물 관리 측면에서 경제적 이익을 취할 수 있을 것으로 예상된다.

**Comment by wogur0915** [comment]
5. 주장하려는 권리

   (1). 토양 습도를 측정하여 측정된 습도값을 습도센서와 통신 모듈의 스레드 변환을 통해 전용 어플리케이션으로만 사용하도록 하는 방법과 습도 단위 재가공 작업
  : ESP32 블루투스 모듈을 통하여 안드로이드 어플리케이션과 아두이노 토양 습도 센서간 쓰레드를 이용한 데이터 송수신 작업과정에서 다른 기기에서는 블루투스 스레드로 받은 정보를    알 수 없도록 우리의 토양습도센서 아두이노 하고만 독립적으로 통신을 통해 주고 받은 스레드 내용을 알 수 있도록 GreenWater의 약자인 GW를 아스키코드 형태에서 2진수 형태로 변환한 71 87 숫자를 스레드의 헤더 부분에 붙여 통신하도록 하고, 토양습도의 경우 어플리케이션에서 이용하기 위해 아래의 자체적인 단위 변환공식을 통한 데이터 정제작업을 한다.

![image](https://user-images.githubusercontent.com/34836246/204125549-f949ae87-5198-45d5-b9fe-c7591ec79b31.png)

   (2.) 변환된 습도값을 이용한 구간별 토양 습도 알림
 : 변환된 습도값이 30% 이상일 경우에는 수분 과다, 10% 이상 30% 미만일 경우에는 수분 적당, 10% 미만일 경우에는 수분 부족 상태를 표시함과 동시에 데이터 네트워크에 연결되지 않았을 때에도 사용자의 어플리케이션에 알림 제공

**Comment by 2gunghyun** [comment]
6. 발명의 용도

  앱 기반 서비스를 통해 식물에 대한 관심도를 높여 추후 소상공인들과의 협의를 통해 모종 판매 서비스로 확장이 가능하다. 더 나아가 LG전자에서 판매중인 ‘틔운’ 제품은 가정에서 식물을 기르는 일반적인 소비자들이 구매하여 사용하기에 가격적인 면과 공간의 제약으로 인해 진입장벽이 높기 때문에, 상대적으로 낮은 단가의 토양습도센서와 아두이노 블루투스 모듈을 이용한 이 제품의 경우 유사한 식물 관리 제품으로써 소비자들로부터 높은 선호도를 가질 수 있다. 또한 추후에 식물 물주는 주기에 대한 데이터를 수집하여 반정형데이터를 확보하여 자동화 스마트 화분의 개발에도 사용될 수 있다.

**Comment by 2gunghyun** [comment]
7. 선행기술 및 참고자료
※ 핵심키워드 : 화분 습도 모니터링, 안드로이드 플랫폼, 모바일 앱, IOT, 블루투스

- 유사특허
  1. (특허) 화분의 습도를 알려주는 습도알림시스템
  발명자 : 문석학, 박현규
  출원인 : 대구과학대학교 산학협력단
  출원일자 :　2021.01.04.
  출원번호 : 1020210000254
  공개번호 : 1020220098484
  화분의 식재공간에 수납된 토양의 수분을 센서부를 통해 측정하고, 측정된 토양의 수분값을 송신부를 통해 스마트기기에 전송한다. 사용자는 전송받은 토양의 수분량을 스마트기기를 통해 확인할 수 있다.


  2. (특허) 습도량 알림 건조대 및 이를 구비한 건조대 습도량 알림 시스템
  발명자 : 박재현, 김소휘, 홍병우, 정수빈, 진현성, 박윤영
  출원인 : 인천대학교 산학협력단
  출원일자 : 2020.12.21.
  출원번호 : 1020200179778
  공개번호 : 1020220089285
  건조대에 널려 있는 세탁물의 습도 정보를 센서를 통해 측정, 측정된 습도 정보를 통해 예상 건조 시간을 계산하고, 계산된 예상 건조 시간을 사용자의 단말기로 전송하여 세탁물 건조 시기를 알려주어 빨래를 제 시간에 걷을 수 있어 낭비되는 시간을 줄일 수 있는 효과가 있다.


- 유사 논문
  1. (논문) 스마트 화분：이재현, 신동우, 황상준,and 이현빈. "스마트 화분." 춘계학술대회 2020.- (2020): 102-102. (http://www.riss.kr/link?id=A107024667)
  기존 화분에 온도, 습도, 광센서를 이용하여 식물에 대해 최적화된 환경을 제공할 수 있도록 하는 장치. 센서들을 통해 정보를 받아들인 뒤 인공지능을 이용하여 그 식물에 대해 최적화된 환경을 제공할 수 있도록 인공지능이 감지한 정보를 인공지능이 식물의 최적화된 환경 데이터에 기반하여 연동된 스마트폰으로 알림을 전송한다.
