### ISSUE TITLE
peer-review 코멘트에 대한 답변들을 생각해 봅시다.

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#23]
- Problem 관련
 (1) 일상에서 느끼는 문제점을 problem으로 놓은 것은 잘한 점이라고 생각합니다. 가능하다면 화분이 죽는 이유가 수분부족으로 죽는다는 것을 시각적으로 보여줄 수 있다면 좋을 것 같습니다. (설문조사, 표 혹은 통계자료)
 (2) 초반의 기획을 보면 수분 부족에 대한 알림이라고 작성이 되어있는데 개선사항에서 이와 관련 없는 여러 센서들이 추가되는 것으로 보입니다. 이에 따른 아웃풋 조정이 필요해 보입니다. 
 
- Solution 관련
  (1) 아두이노 + 블루투스 통신 + 애플리케이션을 이용한 실시간 연동은 좋은 생각 같습니다. 다만 블루투스 통신을 이용하는 경우, 통신 거리의 한계로 인해 사용자가 외출을 했을 경우에는 습도가 어느정도 남았는지 알 수 없지 않는가에 대한 의문점이 남습니다.
  (2) 키우는 식물이 많다면 이에 대한 통제가 어려울 수 있으므로 종류, 물을 준 시간 등으로 묶어서 통제하는 방식을 사용하면 좋을 것 같습니다.
  (3) '농사로’ 사이트 크롤링이 가능 여부를 적어주시면 좋을 것 같고 ‘농사로’ 사이트는 농업 자료가 주 축을 이루고 있어, 타켓으로 삼으시는 일반인 식물 애호가들에게 필요해 보이는 정보는 부족해 보입니다. (단순히 실내에서 키우는 방법에 대해서만 명시하고 있다는 점에서) 사용자가 키우는 식물에 대한 자세한 정보를 인터넷과 연동한 url 검색을 통하여 검색하는 기능이 추가되면 좋을 것 같습니다
  (4) 식물에 따라 적합한 습도의 정도가 다를 텐데 (예를 들어 선인장의 경우에는 물을 주는 주기가 매우 길고 습도가 낮아야 함) 단순히 토양의 습도를 파악해서 습도가 낮을 경우 알림을 주는 것이 아쉽다고 느껴집니다. 식물마다 습도 낮음 알림의 기준을 설정해야 할 것 같고 이를 정확하게 명시해주어야 할 것 같습니다

- 차별성 관련
  (1) 기존 애플리케이션과의 차별성 부분은 기존 특허와의 차별성이 잘 느껴지지 않는다는 점에서 조금 아쉬운 부분이 존재하는 것 같습니다. 그렇지만 보통은 시간에 기반을 둔 알림을 주는데 반해 센서를 이용한다는 방식은 좋다고 생각합니다. 
       엔씽’이라는 기업에서 판매하고 있는 planty라는 스마트 화분이 있습니다. 이 제품은 땅의 습도와 온도를 파악해서 애플리케이션을 통해 확인할 수 있고 화분 자체에 물통이 있어 원격으로 물을 줄 수도 있습니다. 이러한 점에서 토양의 습도만 모니터링 가능한 서비스는 기존 제품과의 차별성이 부족하다고 느껴지고 오히려 기존 제품이 물주기 기능같이 더 많은 기능을 제공한다는 점에서 사용자들이 기존 제품이 아닌 ROOT 팀의 서비스를 이용했을 때의 메리트가 부족하다고 느껴집니다. 
  (2) 개발 시간상 구현이 어려울 수 있다고 생각되지만, 식물의 사진을 찍어 식물을 분석한 뒤, 이 식물의 특징이나 키우는 법을 알려주는 기능이 있으면 차별성을 높일 수 있을 것이라고 생각합니다.

- Evaluation 관련
  (1) 어플리케이션을 통해서 확인한 화분의 토양 습도 정보가 실제 습도와 일치하는지 오차 여부를 검사할 필요가 있다고 생각합니다.

- 그 외
  (1)  토양의 습도를 단순히 텍스트로 명시하는 것이 아닌 그림과 함께 습도에 따라 문구가 바뀐다는 부분이 사용자에게 큰 재미요소가 될 것으로 생각됩니다. 더 나아가 습도에 따라 문구와 함께 화면의 화분의 표정이 바뀌는 등의 요소를 넣으면 더욱 좋을 것 같습니다. 
  (2) 이메일 ID를 사용하는 경우 별도의 보안장치가 없다면 개인정보가 드러나는 위험이 있지 않을까 생각됩니다. 이메일이 없는 일반 ID로 가입하고, 아이디 중복확인을 하는 시스템은 어떨까 싶습니다. + 계정 비밀번호를 분실하였을 시를 대비해 ID로 임시 비밀번호 이메일을 보내거나, 비밀번호 찾기용 질문을 만드는 것은 어떨까 싶습니다

**Comment by wogur0915** [comment]
- Problem 관련 답변
  (1) 
https://botanicpark.seoul.go.kr/front/plants/plantDataView.dosn=881&sCategory=C&searchCondition=&searchKeyword=&pageIndex=1
위 링크를 통해서 들어가 서울 식물원에서 제공하는 식물 정보에 따르면 식물이 시드는 원인은 수분의 과습, 건조 통기성 부족 이 원인이 경우가 대부분이라고 답변해 주었습니다.
  (2) 해당 부분은 발전방향 계획으로, 현재 그러한 센서들은 아직 본 프로젝트에서 적용되지 않은 관계로 만약에 센서들을 추가하게 된다면 그에 맞춰 아웃풋을 조정할 예정입니다.

**Comment by wogur0915** [comment]
- Solution 관련 답변
  (1) 이전에 받았던 질문으로 해당 부분에 대한 추가적인 업데이트를 위해 와이파이 모듈이 포함된 ESP32를 사용중인 상황으로 웹서버를 이용한 통신도 고려하였으나 시간관계상 생략하기로 하였습니다.
  (2) 이것 또한 이전에 받았던 질문으로 저희 팀의 장비개수가 부족한 상황이며 어플리케이션을 설계할 때 일대다 통신이 아닌 일대일 통신을 목표로 두고 설계하였으므로 일단은 본 프로젝트는 식물 한 개에 대해서만 지원하는 방식으로 작동하고 있습니다.
  (3) 농사로에서 가져오는 데이터는 공공 데이터 api를 통해 가져오는 것으로 크롤링과는 무관합니다.
또한 가져오는 데이터가 실내 정원과 관련한 정보이므로 일반적인 가정에서 키우는 식물과 관련된 정보들이 담겨있습니다.
  (4) 건조한 환경에서 자라는 식물의 경우 습도 10% 습한 환경에서 자라는 식물의 경우 30%정도임을 인지하고 있습니다. 식물 모니터링 화면에서 설정 선택을 통해 습도 기준을 변경할 수 있도록 구성할 예정입니다.

**Comment by 2gunghyun** [comment]
- 차별성 관련 답변
(1) 기존 특허는 물주기 알림과 관계가 없는 광센서, 온도센서가 반드시 포함되어있는것에 반해 본 프로젝트는 파츠형식으로 원하는 센서를 부착할 수 있으며 planty의 경우 12만원에 가까운 가격으로 LG의 '틔운' 제품과 마찬가지로 일반 소비자가 소비하기엔 부담스러운 가격이라고 생각되며 이에 우리의 제품이 가격면에서 차별성을 가진다고 생각합니다.
(2) 해당 기능은 실내에서 식물을 기르는 사용자보다 야외에서 활동하는 사용자에게 더 적합한 기능이라고 생각합니다.

**Comment by 2gunghyun** [comment]
- Evaluation 관련
(1) 추후에 실제 시장에 사용되는 토양습도계를 사용하여 본 프로젝트에서 사용되는 토양습도센서의 오차를 확인할 예정입니다.

**Comment by 2gunghyun** [comment]
- 그 외
(1) 이미 초반에 본 프로젝트를 계획할 때 구상하였던 부분입니다.
(2) 개인정보가 드러나는 부분은 구글의 'Firebase'를 사용하여 보안성 부분에선 안전하다고 생각하며 이메일 아이디를 사용하는 부분은 저희가 연락처와 같은 개인정보를 수집하지 않으므로 공지를 보낼때 사용자와 연락할 수단을 확보하기 위하여 이메일 아이디를 작성하도록 한 것입니다. 또한 비밀번호 찾기에 관한 부분은 고려해보겠으나 구현이 어려울 것으로 예상됩니다.

**Comment by wogur0915** [comment]
위 내용들을 Peer-Review 발표 및 답변문서에 반영하여 제출하였습니다.
