### ISSUE TITLE
알람 on off 버튼을 스위치 형식으로 바꾸는 것은 어떨까요?

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#32]
현재는 알람 켜기 버튼과 알람 끄기 버튼 두개로 나누어서 만들어 놓은 상태인데
해당 기능을 구현하기 전 미리 의견을 물어봅니다!
참고로 스위치란 아래의 사진과 같은 모습을 말합니다.
![image](https://user-images.githubusercontent.com/34836246/205551164-fa23b734-fc00-4c77-b247-3777675bdcf9.png)

**Comment by 2gunghyun** [comment]
스위치 방식이 간결해보여서 더 좋은 것 같습니다.

**Comment by wogur0915** [comment]
> 스위치 방식이 간결해보여서 더 좋은 것 같습니다.

의견 감사합니다. 반영하여 수정하도록 하겠습니다!
