### ISSUE TITLE
Api 검색 결과가 검색창을 다시 한번 클릭해야 모든 결과가 출력되는 버그

### ISSUE THREAD

**Issue by 2gunghyun** [wogur0915/GreenWater#38]
![image](https://user-images.githubusercontent.com/74997089/206593966-bd112bbd-aff4-4af2-b2ad-1e1ae797aaf5.png)
검색 시 이와 같이 식물명만 출력이 되는데 여기서 검색창을 클릭해야
![image](https://user-images.githubusercontent.com/74997089/206594104-f245f95a-635d-4b9a-a86f-d07fc7d3a3fd.png)
이와 같이 모든 결과 값이 출력이 됩니다.

**Comment by wogur0915** [comment]
버그 해결로 이슈 닫습니다.
