### ISSUE TITLE
실내정원용 식물 관련 정보를 공유하여봅시다.

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#4]
https://www.nongsaro.go.kr/portal/ps/psz/psza/contentNsMain.ps?menuId=PS03954

농사로 라는 공공데이터 포털에서 실내정원용 식물에 대한 물주기, 광도 등의 정보를 api로 제공하고 있어 참고 차원에서
이슈 남깁니다.

**Comment by 2gunghyun** [comment]
https://url.kr/37xnlc

식물 관리 방법 검색 중 찾은 블로그입니다. 유용할 것 같아 링크 남겨두겠습니다.

**Comment by wogur0915** [comment]
> https://url.kr/37xnlc
> 
> 식물 관리 방법 검색 중 찾은 블로그입니다. 유용할 것 같아 링크 남겨두겠습니다.

아주 좋습니다! 잘 활용해보도록 하겠습니다.
