### ISSUE TITLE
중간고사 발표전 개발 계획입니다.

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#5]
이중현 학우분은 아두이노관련하여 습도측정 코드 및 임시로 lcd 출력하는부분을 구현해주시고
블루투스 모듈을 통한 데이터 전송 관련하여 알아봐주시면 감사하겠습니다.

저 임재혁 은 중간발표까지 최대한 어플리케이션의 대략적인 gui를 구현해볼 생각입니다.

추가로 아두이노 코드같은경우 작업이 빨리 끝날 것 같으므로 어플리케이션의 로그인관련한 부분이나 다른 액티비티 부분을 같이 구현해주시면 감사드리겠습니다.

**Comment by 2gunghyun** [comment]
알겠습니다.  최대한 가능한 만큼 구현 후 도와드리도록 하겠습니다.

**Comment by wogur0915** [comment]
계획 이행 완료로 인하여 이슈 닫겠습니다.
