### ISSUE TITLE
아두이노 우노 보드가 아닌 ESP32 자체에 센서를 장착해보는 건 어떨까요?

### ISSUE THREAD

**Issue by wogur0915** [wogur0915/GreenWater#6]
ESP32 모듈을 구매할 때 터미널 가이드를 같이 구매했어서 해당 터미널가이드에 ESP32모듈을 장착하고 가이드에 있는 포트에 맞게 아두이노 센서 점퍼선들을 꽂아보면 될 것 같은데,
 아두이노 우노보드와 ESP32 그리고 센서까지 모두 따로따로 장착하게되면 부피가 너무 커져서 거추장스러워 질 것이 우려되어 제안드립니다.

![image](https://user-images.githubusercontent.com/34836246/196434592-42be96ce-0bf1-4faa-b51a-7e970319e021.png)

**Comment by 2gunghyun** [comment]
이러면 아두이노 우노 보드를 사용하지 않아도 될 것 같네요. ESP32만 사용하는 것이 괜찮아 보입니다.

**Comment by wogur0915** [comment]
> 이러면 아두이노 우노 보드를 사용하지 않아도 될 것 같네요. ESP32만 사용하는 것이 괜찮아 보입니다.

실험해보았는데 esp32 모듈만 가지고도 정상작동은 되는 것 같아 이렇게 진행해보도록 하겠습니다.
