### ISSUE TITLE
아두이노 온습도센서 코드 실행 중 오류

### ISSUE THREAD

**Issue by 2gunghyun** [wogur0915/GreenWater#7]
![image](https://user-images.githubusercontent.com/74997089/196441345-8e75fb03-95f1-454c-adc0-65a1cb8d8f30.png)
온습도센서 코드를 실행해도 DHT센서가 작동하지 않습니다. 26번핀, 2번핀, VP핀 시도해봤는데 전부 실행되지 않습니다.

**Comment by wogur0915** [comment]
![image](https://user-images.githubusercontent.com/34836246/196445856-c211da6c-0e7a-4fb5-b55a-af9669cd0781.png)

esp32 핍 포트별 상세 안내도 입니다. 해당 설계도를 참고하시어 다른 adc(analog to digital) 핀에 해당하는 포트들에 연결해보시면 될 것같습니다. 그래도 안되신다면 만나서 같이 해결해보도록 해요

**Comment by wogur0915** [comment]
해당 부분은 센서 자체 결함으로 확인되어
온습도센서는 제외하고 토양습도센서로만 작업이 진행되었습니다
e43d9dd4fd0610dbcf6f6a78a6c2b2b111bb3ddf
